version: '3.5'

services:
  prometheus:
    restart: always
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    container_name: prometheus
    hostname: prometheus
    environment:
      TZ: "Europe/Moscow"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    network_mode: host    
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    restart: always
    environment:
      TZ: "Europe/Moscow"

  grafana:
    restart: always
    image: grafana/grafana-enterprise
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Europe/Moscow"

  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    container_name: portainer
    hostname: portainer
    environment:
      TZ: "Europe/Moscow"

volumes:
  prometheus-data:
  grafana-storage:
  portainer_data:
